cmake_minimum_required(VERSION 3.22)
project(cabin_io LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_library(cabin_io_core STATIC cabin_io.cpp)
set_target_properties(cabin_io_core PROPERTIES POSITION_INDEPENDENT_CODE ON)
target_compile_options(cabin_io_core PRIVATE -Wall -Wextra -Werror)
target_include_directories(cabin_io_core PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
if(ANDROID)
    add_library(cabin_io SHARED cabin_jni.cpp)
    target_link_libraries(cabin_io PRIVATE cabin_io_core)
    target_compile_options(cabin_io PRIVATE -Wall -Wextra -Werror)
else()
    enable_testing()
    add_executable(cabin_io_test ../../test/cpp/cabin_io_test.cpp)
    target_link_libraries(cabin_io_test PRIVATE cabin_io_core util pthread)
    target_compile_options(cabin_io_test PRIVATE -Wall -Wextra -Werror)
    add_test(NAME cabin_io_test COMMAND cabin_io_test)
    set_tests_properties(cabin_io_test PROPERTIES TIMEOUT 20)
    add_executable(cabin_i2c_test ../../test/cpp/cabin_i2c_test.cpp)
    target_link_libraries(cabin_i2c_test PRIVATE cabin_io_core pthread)
    target_link_options(cabin_i2c_test PRIVATE -Wl,--wrap=ioctl)
    target_compile_options(cabin_i2c_test PRIVATE -Wall -Wextra -Werror)
    add_test(NAME cabin_i2c_test COMMAND cabin_i2c_test)
    set_tests_properties(cabin_i2c_test PROPERTIES TIMEOUT 20)
    add_executable(cabin_reset_test ../../test/cpp/cabin_reset_test.cpp)
    target_link_libraries(cabin_reset_test PRIVATE cabin_io_core pthread)
    target_link_options(cabin_reset_test PRIVATE -Wl,--wrap=open -Wl,--wrap=write)
    target_compile_options(cabin_reset_test PRIVATE -Wall -Wextra -Werror)
    add_test(NAME cabin_reset_test COMMAND cabin_reset_test)
    set_tests_properties(cabin_reset_test PROPERTIES TIMEOUT 20)
endif()
