package com.cabin.ui.settings

import com.cabin.R

internal fun steeringFunctionLabel(name: String): Int = when (name) {
    "power" -> R.string.steer_func_power
    "mode" -> R.string.steer_func_mode
    "mute" -> R.string.steer_func_mute
    "volume_up" -> R.string.steer_func_volume_up
    "volume_down" -> R.string.steer_func_volume_down
    "previous" -> R.string.steer_func_previous
    "next" -> R.string.steer_func_next
    "navigation" -> R.string.steer_func_navigation
    "phone" -> R.string.steer_func_phone
    "hang_up" -> R.string.steer_func_hang_up
    "play_pause" -> R.string.steer_func_play_pause
    "fast_forward" -> R.string.steer_func_fast_forward
    "rewind" -> R.string.steer_func_rewind
    "home" -> R.string.steer_func_home
    "back" -> R.string.steer_func_back
    "menu" -> R.string.steer_func_menu
    "apps" -> R.string.steer_func_apps
    "eject" -> R.string.steer_func_eject
    "voice" -> R.string.steer_func_voice
    "dim" -> R.string.steer_func_dim
    "recents" -> R.string.steer_func_recents
    "camera" -> R.string.steer_func_camera
    "tone_up" -> R.string.steer_func_tone_up
    "tone_down" -> R.string.steer_func_tone_down
    "band" -> R.string.steer_func_band
    "dvd" -> R.string.steer_func_dvd
    "panorama" -> R.string.steer_func_panorama
    "radio" -> R.string.steer_func_radio
    "screen_off" -> R.string.steer_func_screen_off
    "audio" -> R.string.steer_func_audio
    "video" -> R.string.steer_func_video
    "aux" -> R.string.steer_func_aux
    "bluetooth" -> R.string.steer_func_bluetooth
    "bluetooth_music" -> R.string.steer_func_bluetooth_music
    "equalizer" -> R.string.steer_func_equalizer
    "tv" -> R.string.steer_func_tv
    "ipod" -> R.string.steer_func_ipod
    "car_settings" -> R.string.steer_func_car_settings
    "settings" -> R.string.steer_func_settings
    "standby" -> R.string.steer_func_standby
    "plus" -> R.string.steer_func_plus
    "star" -> R.string.steer_func_star
    "hash" -> R.string.steer_func_hash
    "up" -> R.string.steer_func_up
    "down" -> R.string.steer_func_down
    "left" -> R.string.steer_func_left
    "right" -> R.string.steer_func_right
    "enter" -> R.string.steer_func_enter
    "can_app" -> R.string.steer_func_can_app
    "sd" -> R.string.steer_func_sd
    "usb" -> R.string.steer_func_usb
    "climate" -> R.string.steer_func_climate
    "front_camera" -> R.string.steer_func_front_camera
    "radio_search" -> R.string.steer_func_radio_search
    "radio_scan" -> R.string.steer_func_radio_scan
    "digit_0" -> R.string.steer_func_digit_0
    "digit_1" -> R.string.steer_func_digit_1
    "digit_2" -> R.string.steer_func_digit_2
    "digit_3" -> R.string.steer_func_digit_3
    "digit_4" -> R.string.steer_func_digit_4
    "digit_5" -> R.string.steer_func_digit_5
    "digit_6" -> R.string.steer_func_digit_6
    "digit_7" -> R.string.steer_func_digit_7
    "digit_8" -> R.string.steer_func_digit_8
    "digit_9" -> R.string.steer_func_digit_9
    "camera_1" -> R.string.steer_func_camera_1
    "camera_2" -> R.string.steer_func_camera_2
    "camera_3" -> R.string.steer_func_camera_3
    "camera_4" -> R.string.steer_func_camera_4
    "camera_5" -> R.string.steer_func_camera_5
    else -> R.string.steer_hw_unknown
}
